### ISSUE TITLE
version of source feature not substituted

### ISSUE THREAD

**Issue by missedone** [stempler/bnd-platform#20]
hi @stempler
we're OSGifying testng, project is [here](https://github.com/testng-team/testng-p2).

for the snapshot version, it will be replaced with timestamp qualifier:
```groovy
platform {
	feature(id: 'org.testng.p2.feature', name: 'TestNG Feature') {
		plugin "org.testng:testng:${version}", {
		    bnd {
            	optionalImport 'com.google.common.*'
        	}
			exclude module: 'ant'
		}
	}

	featureId 'org.testng.p2.feature'
	featureName 'TestNG Feature'
	featureVersion versionWithQualifier

	categoryName 'TestNG Libraries'
	categoryId 'org.testng.p2.libraries'

	useBndHashQualifiers false
    defaultQualifier ''

    bnd(group: 'org.testng', name: 'testng', version: "${version}") {
		version = versionWithQualifier
	}
}
```

but one thing i noticed, the source feature version is not substituted (still be '-SNAPSHOT'), org.testng.p2.feature.source_6.9.13.SNAPSHOT-bnd-hApQA.jar:
```
ll build/updatesite/*
-rw-r--r-- 1 nick staff 1.1K Oct 21 04:15 build/updatesite/artifacts.jar
-rw-r--r-- 1 nick staff 2.2K Oct 21 04:15 build/updatesite/content.jar

build/updatesite/features:
total 8.0K
-rw-r--r-- 1 nick staff 419 Oct 21 04:15 org.testng.p2.feature.source_6.9.13.SNAPSHOT-bnd-hApQA.jar
-rw-r--r-- 1 nick staff 453 Oct 21 04:15 org.testng.p2.feature_6.9.13.20161021110925-bnd-9RzSQ.jar

build/updatesite/plugins:
total 2.1M
-rw-r--r-- 1 nick staff  55K Oct 21 04:15 com.beust.jcommander.source_1.48.0.jar
-rw-r--r-- 1 nick staff  63K Oct 21 04:15 com.beust.jcommander_1.48.0.jar
-rw-r--r-- 1 nick staff 296K Oct 21 04:15 org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar
-rw-r--r-- 1 nick staff 385K Oct 21 04:15 org.apache-extras.beanshell.bsh_2.0.0.b6.jar
-rw-r--r-- 1 nick staff 476K Oct 21 04:15 org.testng.source_6.9.13.20161021110925.jar
-rw-r--r-- 1 nick staff 840K Oct 21 04:15 org.testng_6.9.13.20161021110925.jar
```

did I missing anything, or it's a bug?

**Comment by stempler** [comment]
You are actually configuring two different features here. the configuration probably clashes because you use the same feature ID for both.

This configures the overall feature for the whole p2 repo, that is always created:

```groovy
featureId 'org.testng.p2.feature'
featureName 'TestNG Feature'
featureVersion versionWithQualifier
```

This defines a feature based on the scope of plugins configured in the closure:

```groovy
feature(id: 'org.testng.p2.feature', name: 'TestNG Feature') {
  ...
```

You can try two things:
- Remove the `feature` definition above and instead of with `plugin` declare the dependency using `bundle` directly in `platform` **or**
- Change the `id` you provide for the `feature` definition and provide a specific version for that feature

Note that there is also a setting `useFeatureHashQualifiers` if you don't want the hash qualifiers for features.

**Comment by missedone** [comment]
thanks for the clarification, I was though `feature(id: 'org.testng.p2.feature', name: 'TestNG Feature')` was override the platform's one.

now the output looks perfect.
