### ISSUE TITLE
[feature request] support download Eclipse outside of project folder

### ISSUE THREAD

**Issue by missedone** [stempler/bnd-platform#21]
hi @stempler

for now, by default the gradle plugin will download Eclipse to `project.buildDir`, however, I make the gradle build run in travis-ci, the ci job will download Eclipse for each build.
in my mind, this is waste of resources, so I'd like to cache the Eclipse instance in travis-ci. but the problem is looks like I need to specify a location outside of the project in `.travis.yml` for cache.
so i'm thinking can bnd-platform support download Eclipse outside of project folder.

**Comment by missedone** [comment]
after reading PlatformPlugin.groovy, I think one solution is to make `downloadsDir` configurable, 
```
if (extension.downloadsDir == null) {
  downloadsDir = new File(project.buildDir, 'eclipse-downloads')
}
```

if you think this is the right way to go, I'm happy to create a PR.

**Comment by stempler** [comment]
Hi @missedone 

Sounds like a good idea to me. I think making the folder configurable via the *platform* extension is the most flexible approach. Would be great if you create a PR.

It's probably best to remove the member variable `downloadsDir` from the plugin altogether and just use the extension in the tasks where it is needed. Because right now the member variable is set in configuration phase right when applying the plugin when no custom configuration set via the extension is available yet.
