### ISSUE TITLE
Prevent platform_feature creation

### ISSUE THREAD

**Issue by dannmartens** [stempler/bnd-platform#25]
Hi,

I was wondering why there is a need for the platform_feature. 

Isn't it possible to have the features created with their plugin dependencies populated directly? Now all the dependencies are populated at the level of the platform_feature. I could be mistaken, but doesn't that kind of break the feature definitions? 

Cheers,
 Dann

**Comment by dannmartens** [comment]
Hold on, this seems to be a side effect of the Maven dependency I was trying this on. 

>     feature(id: 'org.apache.jena', name: 'Apache Jena', version: '3.1.0') {
        plugin 'org.apache.jena:apache-jena-libs:3.1.0'
    }

**Comment by dannmartens** [comment]
This seems to happen if the artifact is a .pom. Perhaps I am making the wrong assumption, here.
With a similar top-level .pom for GWT, nothing gets included and the feature is empty.

>     feature(id: 'com.google.gwt', name: 'GWT', version: '2.8.0') {
        plugin 'com.google.gwt:gwt:2.8.0'
    }

**Comment by stempler** [comment]
If I remember correctly the platform feature is needed because it describes what is to be content of the p2 repository / update site. If you don't give the same ID to the platform feature as to one of the others you shouldn't have a problem.

I'm not sure, but it might cause problems when you have feature IDs that are equal to bundle symbolic names. So you could try something like `com.google.gwt.feature` your feature's ID.

I'm not sure what you mean with pom dependency - bundles can only be created for Jars, so it might be that it is skipped if it's only artifact is a pom. Might also be that is ignored in the dependency mechanism because there is no Jar.
Does your dependency get properly resolved by Gradle? What is listed for `gradle dependencies`?

**Comment by dannmartens** [comment]
The .pom is a container, a convience construct to get all the jars of GWT. Of course, if it gets ignored, its dependencies will be ignored, as well. Which explains the empty feature.

**Comment by stempler** [comment]
Well, I just say it might. I have no idea how Gradle deals with this kind of dependency. Does it work for you in other Gradle projects?

If your dependency is a so-called bill-of-materials (bom) which is supported in Maven, you might need a third-party plugin to be able to resolve it. See for instance [here](https://spring.io/blog/2015/02/23/better-dependency-management-for-gradle) and [here](https://github.com/lkishalmi/gradle-bom-plugin).

**Comment by stempler** [comment]
Assuming this is solved, as there was no further feedback. Please reopen if that's not the case.
