### ISSUE TITLE
Support for Gradle 3/4

### ISSUE THREAD

**Issue by thugcee** [stempler/bnd-platform#45]
Hi

Are there any plans to support current Gradle version?

Best regards,
Seweryn

**Comment by stempler** [comment]
I must admit I did not test with newer Gradle versions. Mainly because in the projects where I use it, it does not really matter (and I did not do any new OSGi projects for quite some time).

When using it on current Gradle versions, what are the kind of issues you see?
Is it incompatible because of (internal) API changes?

**Comment by thugcee** [comment]
Yes, it's problem with API changes. 
```
  > Declaring custom 'clean' task when using the standard Gradle lifecycle plugins is not allowed.
```
AFAIK support for custom clean tasks has been removed in Gradle 3.0

**Comment by SimonScholz** [comment]
I fixed these issues. Sending more pull requests today :-)
@stempler You can reproduce this issue when applying the java plugin or other plugins derived from the BasePlugin.
